version: '3.3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  web:
    image: uxubisg/yamdb:v1.0
    container_name: web_yamdb
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    entrypoint: prepare.sh
    depends_on:
      - db
    volumes: 
      - ./static:/code/static
  nginx:
    image: nginx:1.19.9-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/django/static:ro
    ports:
      - 80:80
    depends_on:
      - web
